ALTER TABLE user_affiliates
    ADD COLUMN IF NOT EXISTS lottery_points INTEGER NOT NULL DEFAULT 0;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'user_affiliates_lottery_points_nonnegative'
    ) THEN
        ALTER TABLE user_affiliates
            ADD CONSTRAINT user_affiliates_lottery_points_nonnegative
            CHECK (lottery_points >= 0);
    END IF;
END $$;

UPDATE user_affiliates AS inviter
SET lottery_points = invited.invite_count,
    updated_at = NOW()
FROM (
    SELECT inviter_id, COUNT(*)::INTEGER AS invite_count
    FROM user_affiliates
    WHERE inviter_id IS NOT NULL
    GROUP BY inviter_id
) AS invited
WHERE inviter.user_id = invited.inviter_id
  AND inviter.lottery_points = 0;

CREATE TABLE IF NOT EXISTS red_packet_activities (
    id BIGSERIAL PRIMARY KEY,
    period_no BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    name VARCHAR(100) NOT NULL,
    message VARCHAR(255) NOT NULL DEFAULT '',
    packet_type VARCHAR(16) NOT NULL,
    total_amount_cents BIGINT NOT NULL,
    target_participants INTEGER NOT NULL,
    winner_count INTEGER NOT NULL,
    participant_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    recharge_threshold_cents BIGINT NOT NULL DEFAULT 100,
    invitation_points_threshold INTEGER NOT NULL DEFAULT 2,
    invitation_points_cost INTEGER NOT NULL DEFAULT 2,
    recharge_priority BOOLEAN NOT NULL DEFAULT TRUE,
    draw_seed BYTEA,
    published_at TIMESTAMPTZ,
    drawing_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT red_packet_activities_type_check
        CHECK (packet_type IN ('lucky', 'fixed')),
    CONSTRAINT red_packet_activities_status_check
        CHECK (status IN ('draft', 'active', 'drawing', 'completed', 'canceled')),
    CONSTRAINT red_packet_activities_amount_check
        CHECK (total_amount_cents > 0 AND total_amount_cents >= winner_count),
    CONSTRAINT red_packet_activities_participant_check
        CHECK (target_participants > 0 AND participant_count >= 0 AND participant_count <= target_participants),
    CONSTRAINT red_packet_activities_winner_check
        CHECK (winner_count > 0 AND winner_count <= target_participants),
    CONSTRAINT red_packet_activities_fixed_amount_check
        CHECK (packet_type <> 'fixed' OR total_amount_cents % winner_count = 0),
    CONSTRAINT red_packet_activities_eligibility_check
        CHECK (
            recharge_threshold_cents > 0
            AND invitation_points_threshold > 0
            AND invitation_points_cost > 0
        ),
    CONSTRAINT red_packet_activities_seed_check
        CHECK (draw_seed IS NULL OR octet_length(draw_seed) = 32)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_red_packet_single_running
    ON red_packet_activities ((1))
    WHERE status IN ('active', 'drawing');
CREATE INDEX IF NOT EXISTS idx_red_packet_activities_status_period
    ON red_packet_activities (status, period_no DESC);

CREATE TABLE IF NOT EXISTS red_packet_participants (
    id BIGSERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES red_packet_activities(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    qualification_type VARCHAR(24) NOT NULL,
    net_recharge_cents BIGINT NOT NULL DEFAULT 0,
    points_spent INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT red_packet_participants_qualification_check
        CHECK (qualification_type IN ('recharge', 'invitation_points')),
    CONSTRAINT red_packet_participants_values_check
        CHECK (net_recharge_cents >= 0 AND points_spent >= 0),
    UNIQUE (activity_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_red_packet_participants_activity_created
    ON red_packet_participants (activity_id, created_at, id);

CREATE TABLE IF NOT EXISTS invite_lottery_point_ledger (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    action VARCHAR(32) NOT NULL,
    points INTEGER NOT NULL,
    invitee_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    activity_id BIGINT REFERENCES red_packet_activities(id) ON DELETE SET NULL,
    participant_id BIGINT REFERENCES red_packet_participants(id) ON DELETE SET NULL,
    business_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT invite_lottery_point_ledger_action_check
        CHECK (action IN ('invite_grant', 'participation_consume')),
    CONSTRAINT invite_lottery_point_ledger_points_check CHECK (points > 0),
    UNIQUE (business_key)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_invite_lottery_point_grant
    ON invite_lottery_point_ledger (invitee_user_id)
    WHERE action = 'invite_grant' AND invitee_user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_invite_lottery_point_consume
    ON invite_lottery_point_ledger (activity_id, user_id)
    WHERE action = 'participation_consume' AND activity_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_invite_lottery_point_ledger_user_created
    ON invite_lottery_point_ledger (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS red_packet_winners (
    id BIGSERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES red_packet_activities(id) ON DELETE CASCADE,
    participant_id BIGINT NOT NULL REFERENCES red_packet_participants(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount_cents BIGINT NOT NULL,
    is_luckiest BOOLEAN NOT NULL DEFAULT FALSE,
    credited_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT red_packet_winners_amount_check CHECK (amount_cents > 0),
    UNIQUE (activity_id, user_id),
    UNIQUE (activity_id, participant_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_red_packet_one_luckiest
    ON red_packet_winners (activity_id)
    WHERE is_luckiest;

CREATE TABLE IF NOT EXISTS red_packet_reward_ledger (
    id BIGSERIAL PRIMARY KEY,
    activity_id BIGINT NOT NULL REFERENCES red_packet_activities(id) ON DELETE CASCADE,
    winner_id BIGINT NOT NULL REFERENCES red_packet_winners(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    amount_cents BIGINT NOT NULL,
    business_key VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT red_packet_reward_ledger_amount_check CHECK (amount_cents > 0),
    UNIQUE (business_key),
    UNIQUE (winner_id)
);

CREATE INDEX IF NOT EXISTS idx_red_packet_reward_ledger_user_created
    ON red_packet_reward_ledger (user_id, created_at DESC);

COMMENT ON COLUMN user_affiliates.lottery_points IS '邀请抽奖积分，可用于红包活动参与资格';
COMMENT ON TABLE red_packet_activities IS '平台官方红包活动及发布规则快照';
COMMENT ON TABLE red_packet_participants IS '红包活动参与记录';
COMMENT ON TABLE red_packet_winners IS '红包活动中奖与金额分配记录';
COMMENT ON TABLE red_packet_reward_ledger IS '红包奖励余额入账审计流水';
COMMENT ON TABLE invite_lottery_point_ledger IS '邀请抽奖积分增减审计流水';
